name: git-scan
on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request: {}

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  scan:
    if: github.actor!= 'dependabot-preview[bot]'
    name: scan
    runs-on:
      group: Checks
      labels: checks
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: pwd
      - run: ls -la
      - name: Run gitleaks
        id: gitleaks-scan
        run: |
          /usr/local/bin/gitleaks detect \
            --redact \
            -v \
            --log-level=warn \
            --max-target-megabytes=10 \
            --no-git
        continue-on-error: true

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-regex: "Security scan is turned on for this repository.*"

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        if: ${{ steps.gitleaks-scan.outcome == 'failure' }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Security scan is turned on for this repository.
            Please go to [Actions](https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/workflows/required/ParticleMedia/action-workflow/actions/gitleaks/workflow.yaml) check the findings and fix them.
            - gitleaks check ${{ steps.gitleaks-scan.outcome }}
          reactions: eyes
