name: git-scan
on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request: {}
  # Scan mainline branches and report all findings:
  push:
    branches: ["master", "main"]
  # Schedule the CI job (this method uses cron syntax):
  #schedule:
  #  - cron: "20 17 * * *" # Sets cron to scan every day at 17:20 UTC.
jobs:
  scan:
    if: github.actor!= 'dependabot-preview[bot]'
    name: scan
    runs-on:
      group: Checks
      labels: checks
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GIT_LEAKS_LICENSE}}
      - run: pwd
      - run: ls -la
