name: dependency-check
on:
  pull_request:
  push:
    branches:
      - master
      - main

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  pr:
    if: github.event_name == 'pull_request'
    name: pr check
    runs-on:
      group: Checks
      labels: checks
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: pwd
      - run: ls -la

      - name: Run gitleaks
        id: gitleaks-scan
        run: |
          /usr/local/bin/gitleaks detect \
            --redact \
            -v \
            --log-level=warn \
            --max-target-megabytes=10 \
            --no-git
        continue-on-error: true

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-regex: "Security scan is turned on for this repository.*"

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        if: ${{ steps.gitleaks-scan.outcome == 'failure' }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Security scan is turned on for this repository.
            Please go to [Actions](https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/workflows/required/ParticleMedia/action-workflow/actions/gitleaks/workflow.yaml) check the findings and fix them.
            - gitleaks check ${{ steps.gitleaks-scan.outcome }}
          reactions: eyes

  check:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    name: dependency check
    runs-on:
      group: Checks
      labels: checks
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: pwd
      - run: ls -la

      - name: Upload dependency check report
        env:
          DEPENDENCY_TRACK_API_KEY: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
          DEPENDENCY_TRACK_URL: ${{ secrets.DEPENDENCY_TRACK_URL }}
        run: |
          REPO=${{ github.repository }}

          docker run -u 1000:1000 --rm -e CDXGEN_DEBUG_MODE=debug -v /tmp:/tmp -v $(pwd):/app:rw -t ghcr.io/cyclonedx/cdxgen:master -r /app -o /app/bom.json
          curl -X POST "https://${DEPENDENCY_TRACK_URL}/api/v1/bom" \
            -H 'Content-Type: multipart/form-data' \
            -H "X-Api-Key: ${DEPENDENCY_TRACK_API_KEY}" \
            -F "autoCreate=true" \
            -F "projectName=${REPO//\//-}" \
            -F "projectVersion=${{ github.sha }}" \
            -F "bom=@bom.json"
          rm -f bom.json
        continue-on-error: true
